"""In-context test runner — executes Checker-generated pytest cases against Actor code.

Writes Actor source + Checker tests to a sandboxed temp directory, runs pytest,
parses results, and returns structured TestRunResult for the feedback loop.
"""

from __future__ import annotations

import asyncio
import logging
import re
import shutil
import tempfile
import time
from pathlib import Path

from backend.api.schemas.agents import TestCaseResult, TestRunResult

logger = logging.getLogger(__name__)

# Maximum time (seconds) for pytest to run before we kill it.
PYTEST_TIMEOUT = 30


class TestRunner:
    """Sandboxed pytest executor for Actor-generated Python code."""

    async def run(
        self,
        source_code: str,
        test_cases: list[str],
    ) -> TestRunResult:
        """Execute test cases against source code in an isolated temp directory.

        Parameters
        ----------
        source_code : str
            The Actor-generated Python code (written to solution.py).
        test_cases : list[str]
            Checker-generated test snippets. Each is a short assertion or
            test function body.

        Returns
        -------
        TestRunResult with pass/fail counts and pytest output.
        """
        if not test_cases:
            return TestRunResult(executed=False, pytest_output="No test cases provided.")

        if not source_code.strip():
            return TestRunResult(executed=False, pytest_output="No source code provided.")

        start = time.monotonic()
        tmp_dir = Path(tempfile.mkdtemp(prefix="hpema_tests_"))

        try:
            # Write the Actor's code as a module
            solution_path = tmp_dir / "solution.py"
            solution_path.write_text(source_code, encoding="utf-8")

            # Empty conftest.py to mark this as the pytest rootdir
            (tmp_dir / "conftest.py").write_text("", encoding="utf-8")

            # Build the test file
            test_code = self._build_test_file(source_code, test_cases)
            test_path = tmp_dir / "test_solution.py"
            test_path.write_text(test_code, encoding="utf-8")

            # Run pytest
            result = await self._run_pytest(tmp_dir)
            result.execution_time_seconds = round(time.monotonic() - start, 2)
            return result

        except Exception as e:
            logger.exception("Test runner error")
            return TestRunResult(
                executed=True,
                errors=1,
                pytest_output=f"Test runner error: {e}",
                execution_time_seconds=round(time.monotonic() - start, 2),
            )
        finally:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    def _build_test_file(self, source_code: str, test_cases: list[str]) -> str:
        """Construct a valid pytest file from Checker test snippets.

        Strategy:
        - Extract all top-level function/class names from source_code
        - Import them into the test file via `from solution import *`
        - Wrap each test snippet in a proper `def test_N():` function
        - Handle both raw assertions and already-formed test functions
        """
        lines: list[str] = [
            "# Auto-generated by HPEMA test runner",
            "import sys, os",
            "sys.path.insert(0, os.path.dirname(__file__))",
            "import pytest",
            "from solution import *",
            "",
        ]

        for i, tc in enumerate(test_cases, 1):
            tc = tc.strip()
            if not tc:
                continue

            # If the snippet already defines a test function, use it as-is
            if tc.startswith("def test_"):
                lines.append(tc)
                lines.append("")
                continue

            # If it's a raw function like `def main():` with asserts, rename it
            if tc.startswith("def "):
                # Rename to test_N and dedent if needed
                tc = re.sub(r"^def \w+\(", f"def test_case_{i}(", tc, count=1)
                lines.append(tc)
                lines.append("")
                continue

            # Otherwise, wrap bare assertion(s) in a test function
            # Handle multi-line snippets
            snippet_lines = tc.splitlines()
            lines.append(f"def test_case_{i}():")
            for sl in snippet_lines:
                # Strip any `if __name__` guards
                stripped = sl.strip()
                if stripped.startswith("if __name__"):
                    continue
                if stripped.startswith("print("):
                    continue
                # Indent under the test function
                if stripped:
                    lines.append(f"    {stripped}")
            lines.append("")

        return "\n".join(lines)

    async def _run_pytest(self, test_dir: Path) -> TestRunResult:
        """Run pytest in the temp directory and parse results."""
        import os
        import sys

        # Inherit current environment so pytest can find Python + packages.
        # Use --rootdir to isolate from project conftest/pyproject.
        env = os.environ.copy()
        # Ensure the running Python's bin dir is on PATH
        python_bin = str(Path(sys.executable).parent)
        env["PATH"] = f"{python_bin}:{env.get('PATH', '')}"

        try:
            proc = await asyncio.create_subprocess_exec(
                sys.executable, "-m", "pytest",
                str(test_dir / "test_solution.py"),
                "-v",
                "--tb=short",
                "--no-header",
                f"--rootdir={test_dir}",
                "-p", "no:cacheprovider",
                cwd=str(test_dir),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
                env=env,
            )
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(), timeout=PYTEST_TIMEOUT
            )
        except asyncio.TimeoutError:
            proc.kill()
            return TestRunResult(
                executed=True,
                errors=1,
                pytest_output=f"pytest timed out after {PYTEST_TIMEOUT}s",
            )
        except FileNotFoundError:
            return TestRunResult(
                executed=False,
                pytest_output="pytest not found. Install pytest to enable test execution.",
            )

        stdout = stdout_bytes.decode(errors="replace")
        stderr = stderr_bytes.decode(errors="replace")
        combined = f"{stdout}\n{stderr}".strip()

        logger.info(
            "pytest exit=%d stdout=%d bytes stderr=%d bytes",
            proc.returncode, len(stdout), len(stderr),
        )
        logger.debug("pytest combined output:\n%s", combined[:2000])

        # Detect "pytest not installed" — python -m pytest returns exit code 1
        # with "No module named pytest" when pytest isn't available
        if "No module named" in combined and "pytest" in combined:
            return TestRunResult(
                executed=False,
                pytest_output="pytest not installed. Run: pip install pytest",
            )

        # pytest exit codes: 0=all passed, 1=some failed, 2=interrupted,
        # 3=internal error, 4=usage error, 5=no tests collected
        if proc.returncode in (3, 4, 5):
            return TestRunResult(
                executed=True,
                errors=1,
                pytest_output=f"[exit code {proc.returncode}]\n{combined}",
            )

        # Parse individual test results from verbose output.
        # Check combined (stdout+stderr) because some pytest setups
        # write verbose lines to stderr.
        test_results = self._parse_test_results(combined)
        passed = sum(1 for t in test_results if t.passed)
        failed = sum(1 for t in test_results if not t.passed)

        # Fall back to summary line parsing if no individual results found
        if not test_results:
            passed, failed, errors = self._parse_summary(combined)
            total = passed + failed + errors

            # If we still found nothing, report the raw output as an error
            if total == 0 and proc.returncode != 0:
                return TestRunResult(
                    executed=True,
                    errors=1,
                    pytest_output=f"[exit code {proc.returncode}]\n{combined}",
                )

            return TestRunResult(
                executed=True,
                total=total,
                passed=passed,
                failed=failed,
                errors=errors,
                pytest_output=combined,
            )

        return TestRunResult(
            executed=True,
            total=len(test_results),
            passed=passed,
            failed=failed,
            errors=0,
            test_results=test_results,
            pytest_output=combined,
        )

    @staticmethod
    def _parse_test_results(output: str) -> list[TestCaseResult]:
        """Parse pytest -v output for individual test pass/fail lines."""
        results: list[TestCaseResult] = []
        # First pass: collect test names and statuses from verbose lines
        # pytest -v format: "test_solution.py::test_case_1 PASSED"
        for line in output.splitlines():
            m = re.match(r".*?::(\w+)\s+(PASSED|FAILED|ERROR)", line)
            if m:
                results.append(TestCaseResult(
                    name=m.group(1),
                    passed=m.group(2) == "PASSED",
                    error_message="",
                ))

        # Second pass: extract failure details from FAILURES section
        # pytest --tb=short shows: "FAILED test_solution.py::test_case_1 - AssertionError: ..."
        # or a short traceback block per failing test
        failure_details: dict[str, str] = {}
        lines = output.splitlines()
        for i, line in enumerate(lines):
            # Match short-form failure: "FAILED test_solution.py::name - reason"
            m = re.match(r"FAILED\s+.*?::(\w+)\s*-\s*(.*)", line)
            if m:
                failure_details[m.group(1)] = m.group(2).strip()
                continue
            # Match "E       AssertionError" lines in traceback
            if line.strip().startswith("E ") and i > 0:
                # Find which test this belongs to by scanning backwards
                for j in range(i - 1, max(i - 10, -1), -1):
                    tm = re.match(r".*?::(\w+)", lines[j])
                    if tm and tm.group(1) not in failure_details:
                        failure_details[tm.group(1)] = line.strip()[2:].strip()
                        break

        # Attach error messages to results
        for r in results:
            if not r.passed and r.name in failure_details:
                r.error_message = failure_details[r.name]
            elif not r.passed and not r.error_message:
                r.error_message = f"Test {r.name} failed"

        return results

    @staticmethod
    def _parse_summary(output: str) -> tuple[int, int, int]:
        """Parse the pytest summary line: '3 passed, 1 failed, 1 error'."""
        passed = failed = errors = 0
        m = re.search(r"(\d+) passed", output)
        if m:
            passed = int(m.group(1))
        m = re.search(r"(\d+) failed", output)
        if m:
            failed = int(m.group(1))
        m = re.search(r"(\d+) error", output)
        if m:
            errors = int(m.group(1))
        return passed, failed, errors
